apiVersion: v1
kind: Service
metadata:
  name: wisecow-svc
  labels:
    app: wisecow
spec:
  selector:
    app: wisecow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4499
  type: LoadBalancer
